/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import Lab1.Library;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Lab1.Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
